version: '3'

services:
  emqx:
    image: emqx/emqx:latest  # Use latest as per repo examples; pin version for production
    restart: always
    environment:
      - EMQX_NAME=emqx  # Stable node name prefix
      - EMQX_HOST=127.0.0.1  # Localhost for single-node; use network alias/FQDN for clustering
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=securepassword123  # Change to a strong password
      - EMQX_LISTENER__TCP__EXTERNAL=1883  # MQTT TCP listener (updated key per EMQX 5.x config style)
      - EMQX_LISTENER__WS__EXTERNAL=8083  # WebSocket (optional, common in examples)
      - EMQX_LISTENER__SSL__EXTERNAL=8883  # SSL (optional)
      - EMQX_LISTENER__HTTP__MANAGEMENT=8084  # Management API (optional)
      - EMQX_LOG__LEVEL=info
      # - EMQX_LOADED_PLUGINS=emqx_reloader emqx_dashboard  # Example: Load plugins if needed
    ports:
      - 1883    # MQTT TCP
      - 8083    # WebSocket
      - 8084    # HTTP Management API
      - 8883    # MQTT SSL
      - 18083   # Dashboard (HTTP)
    volumes:
      - ../files/emqx-data:/opt/emqx/data  # Persistence for Mnesia database
      - ../files/emqx-etc:/opt/emqx/etc    # Config overrides (bootstrap with defaults)
      - ../files/emqx-log:/opt/emqx/log    # Logs
    healthcheck:
      test: ["CMD-SHELL", "emqx ctl status | grep 'is running'"]  # Repo-recommended status check
      interval: 30s
      timeout: 10s
      retries: 3
    sysctl:  # Kernel tuning for performance (from repo best practices)
      - fs.file-max=2097152
      - fs.nr_open=2097152
      - net.core.somaxconn=32768
      - net.ipv4.tcp_max_syn_backlog=16384
      - net.core.netdev_max_backlog=16384
      - net.ipv4.ip_local_port_range=1000 65535
      - net.core.rmem_default=262144
      - net.core.wmem_default=262144
      - net.core.rmem_max=16777216
      - net.core.wmem_max=16777216
      - net.core.optmem_max=16777216
      - net.ipv4.tcp_rmem=1024 4096 16777216
      - net.ipv4.tcp_wmem=1024 4096 16777216
      - net.ipv4.tcp_max_tw_buckets=1048576
      - net.ipv4.tcp_fin_timeout=15
